#!/bin/bash

WORKSPACE=`dirname $0`
if [ ! -f "$WORKSPACE/bot.conf" ];then
  echo "IS_INSTALLED=0" > $WORKSPACE/bot.conf
fi
source $WORKSPACE/bot.conf

case "$1" in
  init)
    if [ $IS_INSTALLED = 1 ];then
      read -r -p "Bot已经初始化过了，要重新初始化吗？[Y/N]: " input

      case $input in
          [yY][eE][sS]|[yY])
          echo "开始重新初始化"
          ;;

          *)
          exit 0
          ;;
      esac
    fi
    sed -i '/IS_INSTALLED/s/1/0/g' $WORKSPACE/bot.conf
    # 检查环境
    echo "checking python3..."
    sudo apt-get -y install python3 python3-dev python3-venv
    if [ $? != 0 ];then
      echo "安装依赖失败"
      exit 1
    fi
    rm -rf $WORKSPACE/venv && python3 -m venv $WORKSPACE/venv
    if [ $? != 0 ];then
      echo "配置venv失败"
      exit 1
    fi
    echo "checking requirements..."
    source $WORKSPACE/venv/bin/activate
    pip install -r $WORKSPACE/requirements.txt
    if [ $? != 0 ];then
      echo "安装pip包失败"
      exit 1
    fi
    mkdir -p $WORKSPACE/logs
    if [ ! -f "$WORKSPACE/config.py" ]; then
      cp $WORKSPACE/config.py.example $WORKSPACE/config.py
    fi
    if [ ! -f "$WORKSPACE/frp/frpc.ini" ]; then
      cp $WORKSPACE/frp/frpc.ini.example $WORKSPACE/frp/frpc.ini
    fi
    echo ""
    echo "初始化完成，请修改$WORKSPACE/config.py和$WORKSPACE/frp/frpc.ini中的配置，然后执行bot start启动bot"
    sed -i '/IS_INSTALLED/s/0/1/g' $WORKSPACE/bot.conf
  ;;

  start)
# 启动Bot
    if [ $IS_INSTALLED = 0 ];then
      echo "请先执行bot init命令"
      exit 2
    fi
    source $WORKSPACE/venv/bin/activate
    if [ $? != 0 ];then
      exit 1
    fi
    nohup python $WORKSPACE/app.py > $WORKSPACE/logs/app.log 2>&1 &
    if [ $? != 0 ];then
      echo "Bot启动失败"
      exit 1
    fi
    echo "Bot已启动"
    sleep 2
    # 启动frp
    nohup $WORKSPACE/frp/frps -c $WORKSPACE/frp/frps.ini > $WORKSPACE/logs/frps.log 2>&1 &
    if [ $? != 0 ];then
      echo "frps启动失败"
      exit 1
    fi
    echo "frps已启动"
    sleep 2
    nohup $WORKSPACE/frp/frpc -c $WORKSPACE/frp/frpc.ini > $WORKSPACE/logs/frpc.log 2>&1 &
    if [ $? != 0 ];then
      echo "frpc启动失败"
      exit 1
    fi
    echo "frpc已启动"
    tail $WORKSPACE/logs/*
  ;;

  restart)
    $WORKSPACE/bot.sh stop
    $WORKSPACE/bot.sh start
  ;;

  stop)
    echo -ne "bot已停止"
    ps -ef | grep "app.py" | grep -v "grep" | awk '{print $2}' | xargs -n1 kill > /dev/null 2>&1
    echo "OK"
    echo -ne "frp已停止"
    ps -ef | grep "frp" | grep -v "grep" | awk '{print $2}' | xargs -n1 kill > /dev/null 2>&1
    echo "OK"
  ;;

  *)
    echo "Usage: $WORKSPACE/bot {init|start|stop|restart}"
    exit 1
    ;;
esac

exit 0